import Link from "next/link";
import { ArrowRight, BellRing, CheckCircle2, MapPin, RadioTower, Route } from "lucide-react";

import Header from "@/components/layout/HeaderV2";
import Footer from "@/components/layout/FooterV2";
import type { PriorityCitySeo } from "@/lib/seo/priorityCities";

const faqs = (city: PriorityCitySeo) => [
  { question: `Which vehicles can use GPS tracking in ${city.name}?`, answer: `NAVII GPS solutions can support suitable cars, trucks, buses and commercial fleet vehicles based on the selected device, installation and operating requirements.` },
  { question: `Which GPS tracking features are useful for ${city.name} fleets?`, answer: "Common fleet requirements include live location visibility, route history, geofencing, supported vehicle alerts and operational reports." },
  { question: `Can NAVII GPS support vehicles outside ${city.name}?`, answer: `Yes. NAVII GPS provides tracking solutions for operations across ${city.state} and other Indian states, subject to device, network and deployment requirements.` },
  { question: "How do I choose a GPS tracker for my fleet?", answer: "Share the vehicle type, fleet size, routes and required alerts with the NAVII GPS team so a suitable hardware and software workflow can be discussed." },
];

export function CityGpsPage({ city }: { city: PriorityCitySeo }) {
  const url = `https://naviigps.com/gps-tracker/${city.slug}`;
  const hasSeparateStatePage = city.slug !== city.stateSlug;
  const cityFaqs = faqs(city);
  const structuredData = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", "@id": `${url}#webpage`, url, name: `GPS Tracker in ${city.name} | NAVII GPS`, description: `Vehicle GPS tracking and fleet management solutions for ${city.name}, ${city.state}.`, isPartOf: { "@id": "https://naviigps.com/#website" }, about: { "@id": "https://naviigps.com/#organization" }, inLanguage: "en-IN" },
    { "@type": "Service", name: `GPS Tracking Solutions in ${city.name}`, serviceType: "Vehicle GPS Tracking and Fleet Management", provider: { "@id": "https://naviigps.com/#organization" }, areaServed: { "@type": "City", name: city.name, containedInPlace: { "@type": "State", name: city.state } }, url },
    { "@type": "FAQPage", mainEntity: cityFaqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://naviigps.com/" }, { "@type": "ListItem", position: 2, name: "GPS Tracker India", item: "https://naviigps.com/gps-tracker-india" }, ...(hasSeparateStatePage ? [{ "@type": "ListItem", position: 3, name: city.state, item: `https://naviigps.com/gps-tracker/${city.stateSlug}` }, { "@type": "ListItem", position: 4, name: city.name, item: url }] : [{ "@type": "ListItem", position: 3, name: city.name, item: url }])] },
  ] };

  return <><Header /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }} />
    <section className="bg-gradient-to-br from-[#041225] via-[#08224A] to-[#103B82] py-24 text-white md:py-32"><div className="mx-auto max-w-7xl px-6"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-5 py-2 text-sm font-semibold tracking-[0.12em] text-cyan-200"><MapPin size={17} /> {city.name.toUpperCase()}, {city.state.toUpperCase()}</span><h1 className="mt-7 max-w-5xl text-5xl font-extrabold leading-tight md:text-6xl">GPS Tracker in {city.name} for Cars and Commercial Fleets</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200 md:text-xl">NAVII GPS provides vehicle tracking devices and fleet management software for cars, trucks, buses and commercial operations in {city.name} and across {city.state}.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-7 py-4 font-semibold">Request a Consultation <ArrowRight size={19} /></Link><Link href="/products" className="rounded-xl border border-white/20 bg-white/5 px-7 py-4 font-semibold">Explore GPS Devices</Link></div></div></section>
    <section className="bg-white py-20"><div className="mx-auto grid max-w-7xl gap-8 px-6 md:grid-cols-3">{[
      { title: "Live Vehicle Visibility", text: `Monitor the latest location reported by connected vehicles operating across ${city.name}.`, icon: RadioTower },
      { title: "Route and Trip History", text: "Review available journey records to support fleet coordination and route oversight.", icon: Route },
      { title: "Geofences and Alerts", text: "Create location boundaries and monitor supported vehicle and fleet events.", icon: BellRing },
    ].map((feature) => { const Icon = feature.icon; return <article key={feature.title} className="rounded-3xl border border-slate-200 p-8 shadow-sm"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-700"><Icon size={28} /></div><h2 className="mt-5 text-2xl font-bold text-slate-900">{feature.title}</h2><p className="mt-3 leading-7 text-slate-600">{feature.text}</p></article>; })}</div></section>
    <section className="bg-slate-50 py-24"><div className="mx-auto grid max-w-6xl gap-14 px-6 lg:grid-cols-2"><div><span className="text-sm font-semibold tracking-[0.16em] text-blue-700">LOCAL FLEET REQUIREMENTS</span><h2 className="mt-4 text-4xl font-extrabold text-slate-900">Vehicle Tracking for {city.name} Operations</h2><p className="mt-6 text-lg leading-8 text-slate-600">{city.localContext}</p>{city.planningNote && <p className="mt-4 leading-8 text-slate-600">{city.planningNote}</p>}<ul className="mt-8 space-y-4">{city.sectors.map((sector) => <li key={sector} className="flex items-start gap-3 capitalize text-slate-700"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-500" size={20} />{sector}</li>)}</ul></div><div className="rounded-[32px] bg-[#06142E] p-9 text-white shadow-xl"><h3 className="text-3xl font-bold">Coverage Across Key {city.name} Areas</h3><p className="mt-5 leading-8 text-slate-300">Discuss tracking requirements for vehicles operating around {city.areas.join(", ")} and connected routes across {city.state}.</p><div className="mt-7 flex flex-wrap gap-2">{city.areas.map((area) => <span key={area} className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-4 py-2 text-sm text-cyan-100">{area}</span>)}</div><Link href={hasSeparateStatePage ? `/gps-tracker/${city.stateSlug}` : "/gps-tracker-india"} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 font-semibold">{hasSeparateStatePage ? `View ${city.state} Coverage` : "View Pan-India Coverage"} <ArrowRight size={17} /></Link></div></div></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-5xl px-6"><div className="text-center"><span className="text-sm font-semibold tracking-[0.16em] text-blue-700">COMMON QUESTIONS</span><h2 className="mt-3 text-4xl font-extrabold text-slate-900">GPS Tracking in {city.name}: FAQs</h2></div><div className="mt-10 space-y-4">{cityFaqs.map((faq) => <article key={faq.question} className="rounded-2xl border border-slate-200 p-6"><h3 className="text-lg font-bold text-slate-900">{faq.question}</h3><p className="mt-3 leading-7 text-slate-600">{faq.answer}</p></article>)}</div></div></section>
    <section className="bg-[#06142E] py-16 text-white"><div className="mx-auto max-w-5xl px-6 text-center"><h2 className="text-4xl font-extrabold">Plan Your {city.name} Fleet Tracking Setup</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-300">Share your fleet size, vehicle types and operating routes with NAVII GPS.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-7 py-4 font-semibold">Contact NAVII GPS <ArrowRight size={19} /></Link></div></section>
  </main><Footer /></>;
}
