import Link from "next/link";
import { ArrowRight, CheckCircle2, Globe2, MapPin, RadioTower, Route } from "lucide-react";

import Header from "@/components/layout/HeaderV2";
import Footer from "@/components/layout/FooterV2";
import type { InternationalCountrySeo } from "@/lib/seo/internationalCountries";

export function CountryGpsPage({ country }: { country: InternationalCountrySeo }) {
  const url = `https://naviigps.com/gps-tracker/${country.slug}`;
  const faqs = [
    { question: `Can NAVII GPS devices be evaluated for use in ${country.name}?`, answer: `Yes. Device, mobile-network, SIM, installation and regulatory compatibility must be confirmed for the intended vehicles and routes in ${country.name} before deployment.` },
    { question: `Which fleets can use GPS tracking in ${country.name}?`, answer: `Suitable cars, trucks, buses, delivery vehicles and commercial fleets may use compatible tracking devices based on installation and operating requirements.` },
    { question: "Which details are needed for an international deployment review?", answer: "Share the target country, vehicle types, fleet size, routes, required alerts, mobile-network plan and installation responsibility." },
  ];
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "WebPage", "@id": `${url}#webpage`, url, name: `GPS Tracker in ${country.name} | NAVII GPS`, description: `Vehicle GPS tracking devices and fleet software planning for operations in ${country.name}.`, isPartOf: { "@id": "https://naviigps.com/#website" }, inLanguage: "en" },
    { "@type": "Service", name: `GPS Tracking Solutions for ${country.name}`, serviceType: "Vehicle GPS Tracking and Fleet Management", provider: { "@id": "https://naviigps.com/#organization" }, areaServed: { "@type": "Country", name: country.name }, url },
    { "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://naviigps.com/" }, { "@type": "ListItem", position: 2, name: "International GPS Tracking", item: "https://naviigps.com/gps-tracker-international" }, { "@type": "ListItem", position: 3, name: country.name, item: url }] },
  ] };

  return <><Header /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
    <section className="bg-gradient-to-br from-[#041225] via-[#08224A] to-[#103B82] py-24 text-white md:py-32"><div className="mx-auto max-w-7xl px-6"><nav aria-label="Breadcrumb" className="mb-8 flex flex-wrap gap-3 text-sm text-cyan-200"><Link href="/">Home</Link><span>/</span><Link href="/gps-tracker-international">International</Link><span>/</span><span>{country.name}</span></nav><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-5 py-2 text-sm font-semibold tracking-[0.12em] text-cyan-200"><Globe2 size={17} /> INTERNATIONAL FLEET PLANNING</span><h1 className="mt-7 max-w-5xl text-5xl font-extrabold leading-tight md:text-6xl">GPS Tracker in {country.name} for Commercial Fleets</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200 md:text-xl">Explore NAVII GPS vehicle tracking devices and fleet software for operators evaluating deployment in {country.name}. Compatibility and availability are confirmed for the intended vehicles, mobile networks and locations.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-7 py-4 font-semibold">Discuss International Requirements <ArrowRight size={19} /></Link><Link href="/products" className="rounded-xl border border-white/20 bg-white/5 px-7 py-4 font-semibold">Compare GPS Devices</Link></div></div></section>
    <section className="bg-white py-20"><div className="mx-auto grid max-w-7xl gap-8 px-6 md:grid-cols-3">{[{ title: "Latest Vehicle Location", text: "Review the latest position reported by compatible connected devices.", icon: RadioTower }, { title: "Routes and Trip Records", text: "Use available journey history to support dispatch and route review.", icon: Route }, { title: "Operating Areas", text: `Plan requirements for routes around ${country.cities.slice(0, 3).join(", ")} and other locations.`, icon: MapPin }].map((feature) => { const Icon = feature.icon; return <article key={feature.title} className="rounded-3xl border border-slate-200 p-8 shadow-sm"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-100 text-cyan-700"><Icon size={28} /></div><h2 className="mt-5 text-2xl font-bold text-slate-900">{feature.title}</h2><p className="mt-3 leading-7 text-slate-600">{feature.text}</p></article>; })}</div></section>
    <section className="bg-slate-50 py-24"><div className="mx-auto grid max-w-6xl gap-14 px-6 lg:grid-cols-2"><div><p className="text-sm font-semibold tracking-[0.16em] text-blue-700">DEPLOYMENT CONSIDERATIONS</p><h2 className="mt-4 text-4xl font-extrabold text-slate-900">Fleet Tracking for {country.name}</h2><p className="mt-6 text-lg leading-8 text-slate-600">{country.localContext}</p><p className="mt-4 leading-8 text-slate-600">{country.planningNote}</p><ul className="mt-8 space-y-4">{country.sectors.map((sector) => <li key={sector} className="flex items-start gap-3 capitalize text-slate-700"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-500" size={20} />{sector}</li>)}</ul></div><div className="rounded-[32px] bg-[#06142E] p-9 text-white shadow-xl"><h3 className="text-3xl font-bold">Key Operating Locations</h3><p className="mt-5 leading-8 text-slate-300">Discuss vehicle types and planned routes across {country.cities.join(", ")}.</p><div className="mt-7 flex flex-wrap gap-2">{country.cities.map((city) => <span key={city} className="rounded-full border border-cyan-300/20 bg-cyan-300/10 px-4 py-2 text-sm text-cyan-100">{city}</span>)}</div><Link href="/gps-tracker-international" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 font-semibold">International Coverage Guides <ArrowRight size={17} /></Link></div></div></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-5xl px-6"><h2 className="text-center text-4xl font-extrabold text-slate-900">GPS Tracking in {country.name}: FAQs</h2><div className="mt-10 space-y-4">{faqs.map((faq) => <article key={faq.question} className="rounded-2xl border border-slate-200 p-6"><h3 className="text-lg font-bold text-slate-900">{faq.question}</h3><p className="mt-3 leading-7 text-slate-600">{faq.answer}</p></article>)}</div></div></section>
    <section className="bg-[#06142E] py-16 text-white"><div className="mx-auto max-w-5xl px-6 text-center"><h2 className="text-4xl font-extrabold">Plan a Compatible International Fleet Setup</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-300">Share your country, fleet size, vehicle types, mobile-network requirements and operating routes for a compatibility review.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-7 py-4 font-semibold">Contact NAVII GPS <ArrowRight size={19} /></Link></div></section>
  </main><Footer /></>;
}
