import Link from "next/link";
import { ArrowRight, CheckCircle2, MapPin } from "lucide-react";
import Header from "@/components/layout/HeaderV2";
import Footer from "@/components/layout/FooterV2";
import type { IndiaStateSeo } from "@/lib/seo/indiaStates";

export function StateGpsPage({ state }: { state: IndiaStateSeo }) {
  const url = `https://naviigps.com/gps-tracker/${state.slug}`;
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "WebPage", url, name: `GPS Tracker in ${state.name} | NAVII GPS`, inLanguage: "en-IN" }, { "@type": "Service", name: `GPS Tracking Solutions in ${state.name}`, serviceType: "Vehicle GPS Tracking and Fleet Management", provider: { "@id": "https://naviigps.com/#organization" }, areaServed: { "@type": state.unionTerritory ? "AdministrativeArea" : "State", name: state.name }, url }] };
  return <><Header /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><section className="bg-gradient-to-br from-[#041225] via-[#08224A] to-[#103B82] py-24 text-white md:py-32"><div className="mx-auto max-w-7xl px-6"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-5 py-2 text-sm font-semibold text-cyan-200"><MapPin size={17} /> {state.region.toUpperCase()}</span><h1 className="mt-7 max-w-5xl text-5xl font-extrabold leading-tight md:text-6xl">GPS Tracker in {state.name} for Cars and Commercial Fleets</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">Vehicle tracking devices and fleet software planning for operations around {state.cities.join(", ")} and other locations across {state.name}.</p><Link href="/contact" className="mt-9 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-7 py-4 font-semibold">Request a Consultation <ArrowRight size={19} /></Link></div></section><section className="bg-white py-20"><div className="mx-auto grid max-w-6xl gap-10 px-6 lg:grid-cols-2"><div><h2 className="text-4xl font-extrabold text-slate-900">Vehicle Tracking Across {state.name}</h2><ul className="mt-8 space-y-4">{state.sectors.map((sector) => <li key={sector} className="flex gap-3 capitalize text-slate-700"><CheckCircle2 className="shrink-0 text-emerald-500" size={20} />{sector}</li>)}</ul></div><div className="rounded-3xl bg-slate-50 p-8"><h2 className="text-2xl font-bold text-slate-900">Major Operating Locations</h2><p className="mt-5 leading-8 text-slate-600">{state.cities.join(", ")}</p><p className="mt-5 text-sm leading-7 text-slate-500">Device compatibility, network coverage, installation availability and pricing are confirmed for the actual vehicle and location.</p></div></div></section></main><Footer /></>;
}
