import type { Metadata } from "next";

export type InternationalCitySeo = {
  slug: string;
  name: string;
  countrySlug: string;
  countryName: string;
  areas: string[];
  localContext: string;
  planningNote: string;
};

type GeneratedInternationalCitySeo = Omit<
  InternationalCitySeo,
  "localContext" | "planningNote"
> & {
  routeProfile: string;
  planningFocus: string;
};

function createInternationalCity(
  input: GeneratedInternationalCitySeo,
): InternationalCitySeo {
  const { routeProfile, planningFocus, ...city } = input;

  return {
    ...city,
    localContext: `${city.name} fleet operations connect ${routeProfile}, where reliable vehicle location, trip history and event visibility can support dispatch and route coordination.`,
    planningNote: `Before deployment in ${city.name}, confirm ${planningFocus}, compatible mobile networks, device installation responsibility, privacy and workplace requirements, data retention and ongoing platform support.`,
  };
}

const initialInternationalCities: InternationalCitySeo[] = [
  {
    slug: "new-york",
    name: "New York",
    countrySlug: "usa",
    countryName: "United States",
    areas: ["Manhattan", "Brooklyn", "Queens", "The Bronx"],
    localContext: "New York fleets manage dense delivery zones, bridge and tunnel crossings, borough-to-borough service calls and regional routes where timely vehicle status supports dispatch decisions.",
    planningNote: "Review cellular coverage, device certification, installation standards, employee-notice obligations, state and local privacy requirements, data retention and support arrangements before deployment.",
  },
  {
    slug: "los-angeles",
    name: "Los Angeles",
    countrySlug: "usa",
    countryName: "United States",
    areas: ["Downtown Los Angeles", "Long Beach", "Santa Monica", "San Fernando Valley"],
    localContext: "Los Angeles operations span congested urban corridors, port-linked freight routes, wide service territories and scheduled field visits where trip history can assist route and workload review.",
    planningNote: "Confirm supported carrier bands, route coverage, California privacy and employee-monitoring requirements, installation responsibility, alert policies and ongoing platform support before activation.",
  },
  {
    slug: "chicago",
    name: "Chicago",
    countrySlug: "usa",
    countryName: "United States",
    areas: ["The Loop", "O'Hare", "South Side", "West Side"],
    localContext: "Chicago fleets connect central business districts, industrial corridors, airport logistics and interstate freight routes where dependable journey records can support daily operations.",
    planningNote: "Evaluate regional network coverage, winter operating conditions, compatible hardware, installation quality, workplace policies, data access and technical support before fleet rollout.",
  },
  {
    slug: "houston",
    name: "Houston",
    countrySlug: "usa",
    countryName: "United States",
    areas: ["Downtown Houston", "Energy Corridor", "Port Houston", "The Woodlands"],
    localContext: "Houston fleets serve broad metropolitan routes, energy and industrial sites, port activity and regional distribution journeys where vehicle events help coordinate field operations.",
    planningNote: "Validate cellular availability across intended sites, equipment and installation requirements, company vehicle policies, alert escalation, environmental conditions and support ownership before deployment.",
  },
  {
    slug: "dallas",
    name: "Dallas",
    countrySlug: "usa",
    countryName: "United States",
    areas: ["Downtown Dallas", "Fort Worth", "Irving", "Plano"],
    localContext: "Dallas–Fort Worth fleets cover large urban service areas, warehouse clusters, airport routes and interstate distribution corridors where location visibility can improve dispatch coordination.",
    planningNote: "Confirm carrier coverage, supported device bands, installation standards, privacy and workforce policies, reporting requirements, data retention and platform support before procurement.",
  },
  {
    slug: "london",
    name: "London",
    countrySlug: "united-kingdom",
    countryName: "United Kingdom",
    areas: ["Central London", "Heathrow", "Croydon", "Enfield"],
    localContext: "London fleets operate through dense delivery areas, restricted and charging zones, airport corridors and outer-borough service routes where accurate trip records support planning.",
    planningNote: "Review UK data-protection and employee-tracking duties, mobile coverage, device installation, access-zone workflows, data retention and support responsibilities before activation.",
  },
  {
    slug: "birmingham",
    name: "Birmingham",
    countrySlug: "united-kingdom",
    countryName: "United Kingdom",
    areas: ["City Centre", "Digbeth", "Solihull", "West Bromwich"],
    localContext: "Birmingham fleets connect city deliveries, manufacturing areas, motorway junctions and wider West Midlands service routes where route history can support operational review.",
    planningNote: "Confirm network compatibility, clean-air and operating-zone workflows, installation responsibility, UK privacy obligations, driver communication and ongoing platform support before deployment.",
  },
  {
    slug: "manchester",
    name: "Manchester",
    countrySlug: "united-kingdom",
    countryName: "United Kingdom",
    areas: ["Manchester City Centre", "Trafford Park", "Salford", "Stockport"],
    localContext: "Manchester fleets cover urban delivery districts, Trafford Park logistics activity and regional routes across Greater Manchester where vehicle status can assist dispatch teams.",
    planningNote: "Evaluate mobile coverage, compatible devices, installation procedures, UK data and workplace requirements, alert escalation, retention policies and technical support before rollout.",
  },
  {
    slug: "glasgow",
    name: "Glasgow",
    countrySlug: "united-kingdom",
    countryName: "United Kingdom",
    areas: ["Glasgow City Centre", "Clydebank", "Paisley", "East Kilbride"],
    localContext: "Glasgow operations combine city service calls, industrial routes around the Clyde and journeys across the wider urban region where trip records support fleet coordination.",
    planningNote: "Review route and network coverage, low-emission-zone processes, device fitting, UK privacy and employee obligations, reporting access and support arrangements before activation.",
  },
  {
    slug: "leeds",
    name: "Leeds",
    countrySlug: "united-kingdom",
    countryName: "United Kingdom",
    areas: ["Leeds City Centre", "Holbeck", "Seacroft", "Bradford"],
    localContext: "Leeds fleets serve city-centre routes, commercial estates and wider West Yorkshire distribution networks where latest-location information can improve service coordination.",
    planningNote: "Confirm mobile-network suitability, device and installation standards, UK data-protection duties, workforce policies, required reports and ongoing support before deployment.",
  },
  {
    slug: "toronto",
    name: "Toronto",
    countrySlug: "canada",
    countryName: "Canada",
    areas: ["Downtown Toronto", "North York", "Scarborough", "Mississauga"],
    localContext: "Toronto fleets navigate dense urban deliveries, Greater Toronto service territories and major highway corridors where reliable vehicle events can assist dispatch and route review.",
    planningNote: "Validate Canadian carrier bands, regional coverage, winter installation needs, privacy and workplace obligations, data retention, alert access and support responsibilities before rollout.",
  },
  {
    slug: "vancouver",
    name: "Vancouver",
    countrySlug: "canada",
    countryName: "Canada",
    areas: ["Downtown Vancouver", "Burnaby", "Richmond", "Surrey"],
    localContext: "Vancouver fleets connect port and airport logistics, dense metropolitan routes and mountain-linked regional journeys where trip visibility supports changing operating conditions.",
    planningNote: "Review network performance across intended routes, device compatibility, weather-resistant installation, Canadian privacy duties, workforce communication and technical support before activation.",
  },
  {
    slug: "montreal",
    name: "Montreal",
    countrySlug: "canada",
    countryName: "Canada",
    areas: ["Downtown Montreal", "Saint-Laurent", "Laval", "Longueuil"],
    localContext: "Montreal fleets serve island routes, industrial districts, port-linked freight and surrounding metropolitan areas where journey records can support bilingual operating teams.",
    planningNote: "Confirm Quebec and Canadian privacy requirements, language and driver communication needs, cellular coverage, winter-ready installation, data access and platform support before deployment.",
  },
  {
    slug: "calgary",
    name: "Calgary",
    countrySlug: "canada",
    countryName: "Canada",
    areas: ["Downtown Calgary", "Foothills Industrial", "Airport Trail", "Airdrie"],
    localContext: "Calgary fleets cover broad urban routes, industrial parks, energy-sector service journeys and regional highways where latest-location visibility assists field coordination.",
    planningNote: "Evaluate carrier coverage beyond the city, cold-weather device and installation requirements, privacy responsibilities, alert procedures, data retention and support capacity before rollout.",
  },
  {
    slug: "edmonton",
    name: "Edmonton",
    countrySlug: "canada",
    countryName: "Canada",
    areas: ["Downtown Edmonton", "Nisku", "Sherwood Park", "St. Albert"],
    localContext: "Edmonton operations combine city service routes, industrial activity, warehouse movements and long regional journeys where dependable trip data supports fleet oversight.",
    planningNote: "Confirm regional mobile coverage, winter operating and installation standards, Canadian privacy duties, workforce policies, reporting needs and ongoing technical support before activation.",
  },
  {
    slug: "sydney",
    name: "Sydney",
    countrySlug: "australia",
    countryName: "Australia",
    areas: ["Sydney CBD", "Parramatta", "Botany", "Liverpool"],
    localContext: "Sydney fleets operate across congested central routes, port and airport logistics, western business districts and wider metropolitan service territories where trip records aid planning.",
    planningNote: "Validate Australian mobile-network coverage, compatible device bands, installation standards, workplace and privacy requirements, toll-route workflows and support arrangements before deployment.",
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    countrySlug: "australia",
    countryName: "Australia",
    areas: ["Melbourne CBD", "Port Melbourne", "Dandenong", "Tullamarine"],
    localContext: "Melbourne fleets connect central deliveries, port movements, industrial suburbs and regional highway routes where vehicle status can help coordinate varied daily schedules.",
    planningNote: "Review carrier availability, hardware compatibility, professional installation, Australian privacy and employee policies, data retention, alert ownership and platform support before activation.",
  },
  {
    slug: "brisbane",
    name: "Brisbane",
    countrySlug: "australia",
    countryName: "Australia",
    areas: ["Brisbane CBD", "Eagle Farm", "Logan", "Ipswich"],
    localContext: "Brisbane fleets serve fast-growing metropolitan corridors, industrial districts and routes toward surrounding regional centres where journey visibility supports dispatch operations.",
    planningNote: "Confirm network performance across intended routes, device and heat-resistant installation needs, workplace and privacy requirements, reporting access and support responsibilities before rollout.",
  },
  {
    slug: "perth",
    name: "Perth",
    countrySlug: "australia",
    countryName: "Australia",
    areas: ["Perth CBD", "Fremantle", "Welshpool", "Joondalup"],
    localContext: "Perth fleets cover a wide metropolitan footprint, port-linked freight, industrial zones and long regional approaches where dependable location reporting assists operational control.",
    planningNote: "Evaluate mobile coverage outside central areas, compatible hardware, environmental and installation standards, Australian privacy duties, retention needs and technical support before deployment.",
  },
  {
    slug: "adelaide",
    name: "Adelaide",
    countrySlug: "australia",
    countryName: "Australia",
    areas: ["Adelaide CBD", "Port Adelaide", "Wingfield", "Salisbury"],
    localContext: "Adelaide operations combine compact city routes, northern industrial areas, port activity and regional distribution journeys where trip history can support fleet scheduling.",
    planningNote: "Confirm carrier coverage, device compatibility, installation responsibility, Australian workplace and privacy obligations, alert workflows, data retention and ongoing support before activation.",
  },
];

type InternationalCitySeed = [
  slug: string,
  name: string,
  countrySlug: string,
  countryName: string,
  areas: string[],
  routeProfile: string,
  planningFocus: string,
];

const expansionCitySeeds: InternationalCitySeed[] = [
  ["berlin", "Berlin", "germany", "Germany", ["Mitte", "Charlottenburg", "Tempelhof", "Spandau"], "central delivery districts, commercial centres, airport approaches and surrounding logistics corridors", "German and EU data rules, workforce consultation, urban access requirements and route coverage"],
  ["hamburg", "Hamburg", "germany", "Germany", ["HafenCity", "Port of Hamburg", "Altona", "Harburg"], "port terminals, warehouse districts, urban service routes and north-German freight connections", "port operating conditions, cross-border roaming, GDPR duties and professional device fitting"],
  ["munich", "Munich", "germany", "Germany", ["Altstadt", "Schwabing", "Garching", "Freiham"], "busy central routes, technology districts, industrial locations and wider Bavarian service journeys", "urban access workflows, German privacy duties, driver communication and regional network coverage"],
  ["frankfurt", "Frankfurt", "germany", "Germany", ["Innenstadt", "Frankfurt Airport", "Höchst", "Offenbach"], "financial districts, airport logistics, industrial zones and major national road connections", "airport and freight workflows, GDPR compliance, cross-border operations and device certification"],
  ["cologne", "Cologne", "germany", "Germany", ["Innenstadt", "Deutz", "Niehl", "Leverkusen"], "Rhine-side commercial routes, industrial areas, urban deliveries and regional motorway corridors", "mobile coverage, low-emission access, workplace policies and secure fleet-data handling"],
  ["paris", "Paris", "france", "France", ["Central Paris", "La Défense", "Rungis", "Roissy"], "dense central deliveries, business districts, wholesale logistics and airport-linked service routes", "French workplace rules, GDPR responsibilities, restricted-zone planning and installation standards"],
  ["lyon", "Lyon", "france", "France", ["Presqu'île", "Part-Dieu", "Saint-Priest", "Villeurbanne"], "city-centre operations, commercial districts, industrial estates and Rhône corridor distribution routes", "French data obligations, urban access policies, driver notices and cross-region connectivity"],
  ["marseille", "Marseille", "france", "France", ["Old Port", "Fos-sur-Mer", "Marignane", "Aubagne"], "urban service zones, port and petrochemical logistics, airport routes and Mediterranean freight corridors", "port environments, network coverage, GDPR requirements and durable device installation"],
  ["toulouse", "Toulouse", "france", "France", ["City Centre", "Blagnac", "Colomiers", "Montaudran"], "central routes, aerospace districts, airport activity and regional service territories", "industrial-site procedures, French workplace requirements, carrier coverage and reporting access"],
  ["lille", "Lille", "france", "France", ["Euralille", "Lesquin", "Roubaix", "Tourcoing"], "metropolitan deliveries, airport logistics, industrial communities and cross-border Benelux corridors", "international roaming, GDPR compliance, employee policies and route-specific network performance"],
  ["amsterdam", "Amsterdam", "netherlands", "Netherlands", ["Centrum", "Westpoort", "Schiphol", "Zuidoost"], "compact urban routes, port-related activity, airport logistics and regional service networks", "Dutch privacy and workplace duties, environmental-zone workflows, installation and roaming needs"],
  ["rotterdam", "Rotterdam", "netherlands", "Netherlands", ["Port of Rotterdam", "Europoort", "Spaanse Polder", "Dordrecht"], "major port terminals, industrial estates, urban distribution and European freight corridors", "port conditions, cross-border connectivity, GDPR responsibilities and device installation quality"],
  ["the-hague", "The Hague", "netherlands", "Netherlands", ["Centrum", "Binckhorst", "Scheveningen", "Zoetermeer"], "government and business districts, coastal service routes, commercial zones and regional connections", "Dutch workforce policies, privacy compliance, urban route restrictions and secure data access"],
  ["utrecht", "Utrecht", "netherlands", "Netherlands", ["City Centre", "Lage Weide", "Nieuwegein", "Amersfoort"], "central Dutch distribution routes, industrial estates, city services and national motorway links", "coverage across regional corridors, GDPR duties, employee communication and installation responsibility"],
  ["eindhoven", "Eindhoven", "netherlands", "Netherlands", ["City Centre", "Strijp-S", "Veldhoven", "Helmond"], "technology campuses, manufacturing areas, urban deliveries and cross-border regional routes", "industrial access, Dutch privacy requirements, roaming arrangements and fleet support ownership"],
  ["dubai", "Dubai", "uae", "United Arab Emirates", ["Deira", "Jebel Ali", "Dubai South", "Al Quoz"], "high-density commercial districts, port and free-zone logistics, airport corridors and inter-emirate routes", "UAE device and SIM compatibility, operating permissions, heat-resistant fitting and data policies"],
  ["abu-dhabi", "Abu Dhabi", "uae", "United Arab Emirates", ["Mussafah", "Khalifa City", "Yas Island", "Al Reem Island"], "government and commercial districts, industrial zones, island routes and long inter-emirate journeys", "network coverage, local operating requirements, installation standards and fleet-data access controls"],
  ["sharjah", "Sharjah", "uae", "United Arab Emirates", ["Industrial Area", "Al Nahda", "Hamriyah", "Al Sajaa"], "dense commuter routes, industrial districts, free-zone logistics and connections toward Dubai and the northern emirates", "cross-emirate coverage, SIM provisioning, device certification and driver communication"],
  ["ajman", "Ajman", "uae", "United Arab Emirates", ["Al Jurf", "Ajman Industrial", "Al Nuaimiya", "Al Zorah"], "compact urban deliveries, industrial activity, coastal routes and daily inter-emirate service journeys", "carrier performance, compatible hardware, local requirements and reliable professional installation"],
  ["ras-al-khaimah", "Ras Al Khaimah", "uae", "United Arab Emirates", ["Al Nakheel", "Al Hamra", "Al Ghail", "Mina Al Arab"], "city operations, industrial zones, tourism routes and longer movements across the northern emirates", "coverage beyond urban centres, environmental conditions, SIM plans and technical support arrangements"],
  ["riyadh", "Riyadh", "saudi-arabia", "Saudi Arabia", ["Olaya", "Al Sulay", "King Abdullah Financial District", "Second Industrial City"], "large metropolitan service territories, warehouse districts, construction sites and long highway routes", "Saudi network and device requirements, driver policies, installation capacity and data retention"],
  ["jeddah", "Jeddah", "saudi-arabia", "Saudi Arabia", ["Al Balad", "Jeddah Islamic Port", "Al Khomrah", "King Abdulaziz Airport"], "dense urban routes, port freight, southern logistics districts and airport-linked commercial journeys", "coastal operating conditions, device certification, SIM coverage and local fleet procedures"],
  ["dammam", "Dammam", "saudi-arabia", "Saudi Arabia", ["Dammam Industrial Area", "King Abdulaziz Port", "Khobar", "Dhahran"], "Eastern Province cities, port movements, energy-sector sites and regional freight corridors", "industrial-site access, long-route coverage, compatible equipment and alert escalation ownership"],
  ["mecca", "Mecca", "saudi-arabia", "Saudi Arabia", ["Al Aziziyah", "Al Awali", "Al Kakiyyah", "Jabal Al Noor"], "busy urban roads, scheduled transport operations, service districts and routes with changing seasonal demand", "local access requirements, peak-period capacity, network performance and authorized data use"],
  ["medina", "Medina", "saudi-arabia", "Saudi Arabia", ["Central Area", "Qurban", "Al Khalidiyyah", "Medina Industrial City"], "central service routes, industrial activity, airport connections and regional highway journeys", "operating-zone requirements, cellular coverage, device installation and driver communication processes"],
  ["doha", "Doha", "qatar", "Qatar", ["West Bay", "Industrial Area", "Old Airport", "Ras Abu Aboud"], "central business districts, industrial routes, airport approaches and scheduled commercial services", "Qatar network compatibility, operating permissions, installation responsibility and data handling"],
  ["al-rayyan", "Al Rayyan", "qatar", "Qatar", ["Education City", "Al Waab", "Aspire Zone", "Muaither"], "education and sports districts, residential service routes, commercial zones and connections into Doha", "coverage across operating areas, device compatibility, local requirements and alert workflows"],
  ["al-wakrah", "Al Wakrah", "qatar", "Qatar", ["Al Wukair", "Ezdan Oasis", "Mesaieed Road", "Al Wakrah Port"], "growing residential areas, coastal services, port routes and southern industrial connections", "regional coverage, device fitting, operating permissions and support for longer southern routes"],
  ["ras-laffan", "Ras Laffan", "qatar", "Qatar", ["Ras Laffan Industrial City", "Port Area", "North Field Support Zone", "Al Khor Road"], "energy facilities, port terminals, controlled industrial routes and workforce transportation corridors", "industrial access rules, rugged installation, network availability and authorized alert management"],
  ["mesaieed", "Mesaieed", "qatar", "Qatar", ["Mesaieed Industrial City", "Mesaieed Port", "Sealine Road", "Umm Said"], "industrial plants, port logistics, coastal routes and long-distance connections toward Doha", "site permissions, environmental conditions, compatible networks and device maintenance ownership"],
  ["muscat", "Muscat", "oman", "Oman", ["Ruwi", "Ghala", "Rusayl", "Seeb"], "commercial districts, industrial estates, airport routes and coastal highway service operations", "Oman network and SIM compatibility, heat-resistant fitting, route coverage and local procedures"],
  ["sohar", "Sohar", "oman", "Oman", ["Sohar Port", "Freezone Sohar", "Falaj Al Qabail", "Liwa"], "port terminals, free-zone businesses, industrial plants and freight routes toward Muscat and the UAE", "cross-border roaming, industrial access, device durability and installation support"],
  ["salalah", "Salalah", "oman", "Oman", ["Salalah Port", "Raysut", "Awqad", "Thumrait"], "port logistics, industrial areas, urban services and long regional routes across Dhofar", "seasonal weather, remote-route coverage, compatible SIM plans and maintenance arrangements"],
  ["duqm", "Duqm", "oman", "Oman", ["Port of Duqm", "Special Economic Zone", "Haima Road", "Dry Dock Area"], "port construction, special-zone industry, dry-dock operations and remote highway journeys", "remote network availability, rugged hardware, environmental installation standards and support response"],
  ["nizwa", "Nizwa", "oman", "Oman", ["Nizwa Industrial Estate", "Birkat Al Mouz", "Adam Road", "Bahla Road"], "regional commerce, industrial-estate routes, service journeys and inland highway connections", "coverage across interior routes, device compatibility, installation quality and SIM provisioning"],
  ["kuwait-city", "Kuwait City", "kuwait", "Kuwait", ["Sharq", "Shuwaikh", "Al Rai", "Kuwait Free Trade Zone"], "central commercial districts, port-linked routes, warehouse areas and metropolitan service operations", "Kuwait network support, device compatibility, heat-resistant fitting and local data procedures"],
  ["al-ahmadi", "Al Ahmadi", "kuwait", "Kuwait", ["Ahmadi Industrial Area", "Mina Al Ahmadi", "Fahaheel", "Mangaf"], "energy-sector sites, industrial roads, coastal logistics and employee transport routes", "industrial permissions, environmental conditions, reliable coverage and alert escalation processes"],
  ["farwaniya", "Farwaniya", "kuwait", "Kuwait", ["Farwaniya Industrial Area", "Kuwait Airport", "Jleeb Al-Shuyoukh", "Ardiya"], "airport logistics, dense commercial routes, warehouse districts and metropolitan deliveries", "airport and industrial workflows, SIM performance, professional installation and data access"],
  ["hawally", "Hawally", "kuwait", "Kuwait", ["Hawally District", "Salmiya", "Jabriya", "Bayan"], "dense residential services, retail deliveries, coastal commercial routes and scheduled field visits", "urban coverage, driver policies, device placement and authorized location-data handling"],
  ["shuwaikh", "Shuwaikh", "kuwait", "Kuwait", ["Shuwaikh Industrial", "Shuwaikh Port", "Shuwaikh Free Trade Zone", "Al Rai"], "port freight, industrial workshops, wholesale markets and high-volume warehouse movements", "port and industrial conditions, hardware durability, network coverage and installation responsibility"],
  ["manama", "Manama", "bahrain", "Bahrain", ["Diplomatic Area", "Seef", "Salmaniya", "Bahrain Bay"], "central business districts, retail and service routes, waterfront developments and island-wide journeys", "Bahrain network compatibility, local policies, device installation and secure data access"],
  ["muharraq", "Muharraq", "bahrain", "Bahrain", ["Bahrain International Airport", "Hidd", "Amwaj Islands", "Galali"], "airport logistics, port connections, residential services and routes across the northern islands", "airport operating procedures, SIM coverage, installation requirements and fleet alert ownership"],
  ["riffa", "Riffa", "bahrain", "Bahrain", ["East Riffa", "West Riffa", "Riffa Industrial Area", "Isa Town"], "urban service areas, industrial routes, commercial districts and connections toward Manama", "network coverage, device compatibility, workforce procedures and platform support arrangements"],
  ["sitra", "Sitra", "bahrain", "Bahrain", ["Sitra Industrial Area", "Sitra Wharf", "Ma'ameer", "Nabih Saleh"], "industrial plants, wharf operations, energy logistics and short inter-island commercial routes", "industrial access, environmental installation needs, reliable connectivity and data responsibilities"],
  ["hidd", "Hidd", "bahrain", "Bahrain", ["Bahrain Logistics Zone", "Khalifa Bin Salman Port", "Hidd Industrial Area", "Arad"], "port terminals, logistics parks, industrial estates and airport-linked freight routes", "port workflows, device durability, local network compatibility and support response procedures"],
  ["jurong", "Jurong", "singapore", "Singapore", ["Jurong Industrial Estate", "Jurong Port", "Tuas Link", "Jurong Innovation District"], "industrial estates, port freight, technology facilities and scheduled western-region routes", "Singapore regulatory duties, port access, supported networks and secure fleet-data handling"],
  ["tuas", "Tuas", "singapore", "Singapore", ["Tuas Port", "Tuas South", "Tuas Biomedical Park", "Tuas View"], "major port operations, industrial plants, logistics facilities and cross-island freight journeys", "port and site permissions, device installation, network coverage and data governance"],
  ["changi", "Changi", "singapore", "Singapore", ["Changi Airport", "Changi Business Park", "Loyang", "Tampines Logistics Park"], "airport cargo, business parks, aerospace services and eastern commercial delivery routes", "airport procedures, Singapore privacy rules, compatible connectivity and alert access controls"],
  ["woodlands", "Woodlands", "singapore", "Singapore", ["Woodlands Regional Centre", "Senoko", "Admiralty", "Marsiling"], "northern commercial districts, industrial facilities, residential services and cross-border approaches", "border-route operations, roaming needs, local network coverage and authorized data use"],
  ["tampines", "Tampines", "singapore", "Singapore", ["Tampines Regional Centre", "Tampines North", "Changi South", "Pasir Ris"], "regional business districts, residential deliveries, airport-support zones and eastern service routes", "urban operating requirements, device fitting, data protection and dispatch alert workflows"],
  ["kuala-lumpur", "Kuala Lumpur", "malaysia", "Malaysia", ["City Centre", "Bukit Bintang", "Sungai Besi", "Kepong"], "dense commercial districts, urban deliveries, industrial routes and Greater Kuala Lumpur journeys", "Malaysian network coverage, device compatibility, local data duties and installation support"],
  ["selangor", "Selangor", "malaysia", "Malaysia", ["Shah Alam", "Petaling Jaya", "Puchong", "Subang Jaya"], "large metropolitan service territories, manufacturing zones, warehouse clusters and highway corridors", "multi-carrier coverage, regional route needs, professional fitting and workforce procedures"],
  ["johor-bahru", "Johor Bahru", "malaysia", "Malaysia", ["Pasir Gudang", "Tanjung Pelepas", "Skudai", "Iskandar Puteri"], "port logistics, industrial districts, cross-border approaches and southern regional distribution routes", "Malaysia-Singapore roaming, port access, device certification and data handling responsibilities"],
  ["penang", "Penang", "malaysia", "Malaysia", ["George Town", "Bayan Lepas", "Perai", "Batu Kawan"], "island deliveries, manufacturing hubs, bridge crossings and mainland logistics corridors", "cross-island coverage, industrial requirements, SIM compatibility and installation quality"],
  ["port-klang", "Port Klang", "malaysia", "Malaysia", ["Northport", "Westports", "Pulau Indah", "Klang Industrial Area"], "container terminals, free zones, warehouse districts and routes across the Klang Valley", "port permissions, rugged equipment, reliable network performance and alert escalation ownership"],
  ["auckland", "Auckland", "new-zealand", "New Zealand", ["Auckland CBD", "East Tamaki", "Auckland Airport", "Wiri"], "dense metropolitan deliveries, industrial estates, airport logistics and routes across the wider Auckland region", "New Zealand privacy and employment duties, regional carrier coverage, installation quality and data access"],
  ["wellington", "Wellington", "new-zealand", "New Zealand", ["Wellington CBD", "Seaview", "Porirua", "Lower Hutt"], "central business routes, port activity, Hutt Valley industry and scheduled services across the metropolitan area", "hilly-route coverage, workplace policies, device compatibility and reliable installation support"],
  ["christchurch", "Christchurch", "new-zealand", "New Zealand", ["Christchurch CBD", "Hornby", "Rolleston", "Lyttelton Port"], "urban distribution, industrial parks, port logistics and regional journeys across Canterbury", "regional network performance, weather conditions, New Zealand data duties and maintenance responsibility"],
  ["hamilton", "Hamilton", "new-zealand", "New Zealand", ["Hamilton Central", "Te Rapa", "Ruakura", "Cambridge"], "city services, inland logistics hubs, agricultural supply routes and connections across the Waikato region", "rural-route coverage, compatible SIM plans, installation standards and authorized location-data use"],
  ["tauranga", "Tauranga", "new-zealand", "New Zealand", ["Port of Tauranga", "Mount Maunganui", "Tauriko", "Te Puke"], "port freight, industrial estates, coastal deliveries and regional Bay of Plenty transport corridors", "port workflows, regional coverage, equipment durability and fleet alert escalation ownership"],
  ["rome", "Rome", "italy", "Italy", ["Centro Storico", "EUR", "Fiumicino", "Tiburtina"], "historic central routes, business districts, airport connections and regional service journeys across Lazio", "Italian access-zone rules, GDPR and workplace duties, carrier coverage and professional installation"],
  ["milan", "Milan", "italy", "Italy", ["Centro Direzionale", "Porta Nuova", "Linate", "Sesto San Giovanni"], "dense commercial deliveries, financial districts, airport routes and northern industrial corridors", "low-emission access, Italian employee policies, cross-border roaming and secure fleet-data handling"],
  ["naples", "Naples", "italy", "Italy", ["Naples Port", "Centro Direzionale", "Capodichino", "Nola"], "busy urban routes, port freight, airport activity and distribution connections across Campania", "urban and port operating conditions, mobile coverage, GDPR requirements and device fitting"],
  ["turin", "Turin", "italy", "Italy", ["Centro", "Mirafiori", "Lingotto", "Orbassano"], "city deliveries, automotive districts, industrial estates and cross-border freight routes in Piedmont", "industrial-site access, roaming needs, workforce consultation and compatible network coverage"],
  ["bologna", "Bologna", "italy", "Italy", ["Bologna Centrale", "Interporto", "Borgo Panigale", "Imola"], "central distribution routes, intermodal logistics, industrial areas and major north-south motorway connections", "restricted-zone workflows, Italian privacy obligations, installation responsibility and route coverage"],
  ["madrid", "Madrid", "spain", "Spain", ["Centro", "Barajas", "Villaverde", "Coslada"], "large metropolitan service areas, airport cargo, industrial districts and national motorway corridors", "Spanish data and workplace duties, environmental-zone access, device compatibility and network coverage"],
  ["barcelona", "Barcelona", "spain", "Spain", ["Eixample", "Zona Franca", "Port of Barcelona", "El Prat"], "dense urban deliveries, port and free-zone logistics, airport routes and Mediterranean freight corridors", "low-emission access, port workflows, GDPR compliance and cross-border connectivity"],
  ["valencia", "Valencia", "spain", "Spain", ["Valencia Port", "Ciutat Vella", "Paterna", "Sagunto"], "major port terminals, city distribution, industrial parks and regional coastal transport routes", "port requirements, carrier performance, professional fitting and authorized fleet-data use"],
  ["seville", "Seville", "spain", "Spain", ["Casco Antiguo", "Cartuja", "Dos Hermanas", "Alcalá de Guadaíra"], "historic urban routes, commercial districts, industrial estates and regional Andalusian journeys", "restricted-area planning, heat-resistant installation, Spanish workplace rules and support coverage"],
  ["bilbao", "Bilbao", "spain", "Spain", ["Abando", "Port of Bilbao", "Barakaldo", "Basauri"], "city service routes, port freight, industrial communities and northern cross-border corridors", "port and industrial access, roaming arrangements, GDPR responsibilities and device durability"],
  ["brussels", "Brussels", "belgium", "Belgium", ["European Quarter", "Brussels Airport", "Anderlecht", "Vilvoorde"], "central business routes, institutional districts, airport logistics and metropolitan distribution operations", "Belgian privacy and workplace rules, low-emission access, multilingual operations and installation standards"],
  ["antwerp", "Antwerp", "belgium", "Belgium", ["Port of Antwerp-Bruges", "Deurne", "Merksem", "Wilrijk"], "major port terminals, petrochemical zones, urban deliveries and international freight corridors", "port safety processes, cross-border roaming, GDPR duties and rugged device installation"],
  ["ghent", "Ghent", "belgium", "Belgium", ["North Sea Port", "Gentbrugge", "Zwijnaarde", "Evergem"], "port-linked industry, city services, technology campuses and routes across East Flanders", "industrial access, regional coverage, employee policies and secure location-data management"],
  ["liege", "Liège", "belgium", "Belgium", ["Liège Airport", "Seraing", "Herstal", "Bierset"], "air-cargo logistics, industrial districts, urban services and cross-border road connections", "airport workflows, international roaming, Belgian workplace duties and alert responsibility"],
  ["charleroi", "Charleroi", "belgium", "Belgium", ["Charleroi Airport", "Gosselies", "Marchienne-au-Pont", "Fleurus"], "airport activity, industrial communities, commercial routes and regional Wallonia distribution", "carrier coverage, low-emission planning, installation quality and GDPR-compliant data access"],
  ["zurich", "Zurich", "switzerland", "Switzerland", ["City Centre", "Zurich Airport", "Altstetten", "Oerlikon"], "financial districts, airport logistics, urban services and regional motorway connections", "Swiss privacy and employment rules, network compatibility, restricted-zone planning and roaming"],
  ["geneva", "Geneva", "switzerland", "Switzerland", ["City Centre", "Geneva Airport", "Meyrin", "Vernier"], "international business districts, airport routes, service fleets and cross-border French connections", "Swiss and cross-border data duties, roaming performance, employee policies and device fitting"],
  ["basel", "Basel", "switzerland", "Switzerland", ["Port of Switzerland", "Kleinhüningen", "Pratteln", "Muttenz"], "Rhine port logistics, pharmaceutical industry, urban distribution and tri-border freight corridors", "cross-border connectivity, industrial-site requirements, Swiss data rules and secure installation"],
  ["bern", "Bern", "switzerland", "Switzerland", ["Old City", "Wankdorf", "Ostermundigen", "Belp"], "government and commercial routes, regional services, airport approaches and journeys across the Swiss plateau", "regional terrain coverage, workplace obligations, compatible devices and ongoing technical support"],
  ["lausanne", "Lausanne", "switzerland", "Switzerland", ["Lausanne Centre", "Ouchy", "Renens", "Ecublens"], "hilly urban deliveries, lakeside services, university districts and western Swiss regional routes", "terrain-specific coverage, French-speaking operations, Swiss privacy duties and installation quality"],
  ["dublin", "Dublin", "ireland", "Ireland", ["Dublin City Centre", "Dublin Port", "Dublin Airport", "Ballymount"], "dense urban deliveries, port freight, airport logistics and national motorway connections", "Irish and EU data duties, employee policies, network compatibility and professional installation"],
  ["cork", "Cork", "ireland", "Ireland", ["Cork City Centre", "Ringaskiddy", "Little Island", "Cork Airport"], "city services, port and pharmaceutical logistics, industrial estates and southern regional routes", "port workflows, regional coverage, GDPR responsibilities and durable device fitting"],
  ["limerick", "Limerick", "ireland", "Ireland", ["Limerick City", "Raheen", "Castletroy", "Shannon"], "urban distribution, industrial parks, airport connections and western motorway corridors", "cross-county coverage, workplace requirements, compatible SIM plans and alert management"],
  ["galway", "Galway", "ireland", "Ireland", ["Galway City", "Parkmore", "Oranmore", "Ballybrit"], "city deliveries, technology and medical-device districts, coastal services and western regional journeys", "coastal and rural coverage, Irish privacy duties, installation support and data retention"],
  ["waterford", "Waterford", "ireland", "Ireland", ["Waterford City", "Belview Port", "Tramore", "Dungarvan"], "port-linked distribution, city services, coastal routes and connections across the south-east", "regional carrier performance, port access, employee communication and maintenance responsibility"],
  ["lisbon", "Lisbon", "portugal", "Portugal", ["Baixa", "Parque das Nações", "Lisbon Airport", "Loures"], "dense central deliveries, riverside commercial districts, airport logistics and routes across the Lisbon metropolitan area", "Portuguese privacy and workplace duties, low-emission access, network coverage and installation quality"],
  ["porto", "Porto", "portugal", "Portugal", ["Porto Centre", "Matosinhos", "Maia", "Vila Nova de Gaia"], "urban service routes, port-linked industry, warehouse districts and northern regional distribution corridors", "port operations, regional carrier coverage, GDPR compliance and professional device fitting"],
  ["braga", "Braga", "portugal", "Portugal", ["Braga Centre", "Celeirós", "Famalicão", "Guimarães"], "city deliveries, industrial parks, commercial communities and routes across the Minho region", "cross-municipal coverage, workforce policies, compatible SIM plans and secure data access"],
  ["coimbra", "Coimbra", "portugal", "Portugal", ["Coimbra Centre", "Taveiro", "Eiras", "Figueira da Foz"], "urban services, university districts, industrial zones and central Portuguese regional journeys", "regional network performance, Portuguese data obligations, device placement and support ownership"],
  ["faro", "Faro", "portugal", "Portugal", ["Faro Centre", "Faro Airport", "Loulé", "Olhão"], "airport activity, tourism services, coastal deliveries and longer routes across the Algarve", "seasonal fleet demand, coastal route coverage, installation standards and authorized data handling"],
  ["vienna", "Vienna", "austria", "Austria", ["Innere Stadt", "Vienna Airport", "Simmering", "Donaustadt"], "central commercial routes, airport logistics, industrial districts and international Danube corridor journeys", "Austrian workplace and GDPR duties, urban access, roaming compatibility and device installation"],
  ["graz", "Graz", "austria", "Austria", ["Innere Stadt", "Puntigam", "Liebenau", "Premstätten"], "city deliveries, automotive industry, logistics estates and southern cross-border routes", "industrial access, Austrian employee policies, cross-border coverage and fleet-data security"],
  ["linz", "Linz", "austria", "Austria", ["Linz Centre", "Port of Linz", "Industriezeile", "Traun"], "Danube port operations, heavy industry, urban distribution and national freight connections", "industrial environments, network reliability, GDPR requirements and durable device fitting"],
  ["salzburg", "Salzburg", "austria", "Austria", ["Altstadt", "Salzburg Airport", "Liefering", "Wals-Siezenheim"], "historic urban routes, airport services, commercial zones and alpine cross-border corridors", "restricted-area planning, alpine coverage, roaming needs and professional installation responsibility"],
  ["innsbruck", "Innsbruck", "austria", "Austria", ["Innsbruck Centre", "Innsbruck Airport", "Hall in Tirol", "Völs"], "mountain-city services, airport routes, logistics estates and Brenner corridor freight movements", "tunnel and alpine coverage, winter conditions, Austrian data duties and hardware compatibility"],
  ["copenhagen", "Copenhagen", "denmark", "Denmark", ["City Centre", "Copenhagen Airport", "Nordhavn", "Hvidovre"], "dense urban deliveries, airport logistics, port districts and cross-border bridge connections", "Danish workplace and GDPR rules, environmental zones, roaming performance and installation standards"],
  ["aarhus", "Aarhus", "denmark", "Denmark", ["Aarhus Centre", "Port of Aarhus", "Skejby", "Viby"], "city services, container port operations, business districts and regional Jutland distribution routes", "port workflows, regional coverage, employee policies and secure location-data management"],
  ["odense", "Odense", "denmark", "Denmark", ["Odense Centre", "Tietgenbyen", "Munkebo", "Nyborg"], "urban deliveries, technology and logistics parks, industrial routes and Funen motorway connections", "bridge-route connectivity, Danish data duties, device compatibility and support responsibility"],
  ["aalborg", "Aalborg", "denmark", "Denmark", ["Aalborg Centre", "Port of Aalborg", "Nørresundby", "Aalborg East"], "city operations, port and energy activity, industrial districts and northern Jutland routes", "regional carrier coverage, port conditions, professional fitting and authorized alert access"],
  ["esbjerg", "Esbjerg", "denmark", "Denmark", ["Port of Esbjerg", "Esbjerg Centre", "Varde", "Bramming"], "offshore energy logistics, port terminals, commercial services and western Danish regional journeys", "offshore support workflows, coastal network coverage, device durability and data governance"],
  ["stockholm", "Stockholm", "sweden", "Sweden", ["Norrmalm", "Värtahamnen", "Solna", "Arlanda Airport"], "central business routes, port activity, airport logistics and services across the wider capital region", "Swedish privacy and workplace rules, environmental zones, winter coverage and installation quality"],
  ["gothenburg", "Gothenburg", "sweden", "Sweden", ["Port of Gothenburg", "Hisingen", "Mölndal", "Landvetter Airport"], "major port freight, automotive industry, airport routes and western Scandinavian logistics corridors", "port operations, cross-border roaming, winter conditions and secure fleet-data handling"],
  ["malmo", "Malmö", "sweden", "Sweden", ["Malmö Centre", "Norra Hamnen", "Hyllie", "Fosie"], "urban deliveries, port-linked industry, commercial districts and Öresund cross-border connections", "bridge and roaming requirements, Swedish employee duties, low-emission access and device fitting"],
  ["uppsala", "Uppsala", "sweden", "Sweden", ["Uppsala Centre", "Boländerna", "Fyrislund", "Arlanda Corridor"], "city services, life-science districts, logistics zones and regional routes toward Stockholm", "regional coverage, Swedish data obligations, winter performance and alert workflow ownership"],
  ["vasteras", "Västerås", "sweden", "Sweden", ["Västerås Centre", "Västerås Port", "Finnslätten", "Hacksta"], "lake port logistics, industrial manufacturing, urban services and central Swedish freight routes", "industrial-site access, network reliability, privacy compliance and professional installation"],
  ["oslo", "Oslo", "norway", "Norway", ["Oslo Centre", "Alnabru", "Oslo Port", "Gardermoen"], "dense urban routes, national logistics hubs, port activity and airport freight connections", "Norwegian privacy and workforce duties, toll and access workflows, winter coverage and fitting standards"],
  ["bergen", "Bergen", "norway", "Norway", ["Bergen Centre", "Bergen Port", "Kokstad", "Åsane"], "port and maritime services, hilly urban deliveries, industrial areas and western coastal routes", "tunnel and mountain coverage, coastal weather, employee policies and device durability"],
  ["trondheim", "Trondheim", "norway", "Norway", ["Trondheim Centre", "Torgård", "Nyhavna", "Stjørdal"], "urban distribution, technology districts, port logistics and long central Norwegian journeys", "winter and remote-route connectivity, data requirements, installation support and SIM compatibility"],
  ["stavanger", "Stavanger", "norway", "Norway", ["Stavanger Centre", "Forus", "Risavika", "Sola Airport"], "energy-sector services, port routes, airport logistics and commercial operations across Rogaland", "energy-site procedures, coastal coverage, Norwegian data duties and alert escalation ownership"],
  ["drammen", "Drammen", "norway", "Norway", ["Drammen Centre", "Drammen Port", "Lierstranda", "Kobbervikdalen"], "vehicle imports, port logistics, industrial estates and routes connecting Oslo with southern Norway", "port workflows, winter performance, compatible hardware and professional installation responsibility"],
  ["helsinki", "Helsinki", "finland", "Finland", ["Helsinki Centre", "Vuosaari Port", "Pasila", "Vantaa Airport"], "central services, container port freight, commercial districts and airport logistics across the capital region", "Finnish privacy and workplace duties, winter coverage, network compatibility and secure data access"],
  ["espoo", "Espoo", "finland", "Finland", ["Keilaniemi", "Leppävaara", "Kivenlahti", "Juvanmalmi"], "technology campuses, business districts, industrial zones and metropolitan service routes", "regional connectivity, employee policies, cold-weather hardware and installation quality"],
  ["tampere", "Tampere", "finland", "Finland", ["Tampere Centre", "Hervanta", "Sarankulma", "Pirkkala Airport"], "city distribution, technology and manufacturing areas, airport routes and inland national corridors", "winter network performance, Finnish data rules, device compatibility and maintenance ownership"],
  ["turku", "Turku", "finland", "Finland", ["Port of Turku", "Turku Centre", "Pansio", "Raisio"], "ferry and port logistics, urban deliveries, industrial districts and routes toward Helsinki", "ferry connectivity, port access, GDPR responsibilities and rugged installation standards"],
  ["oulu", "Oulu", "finland", "Finland", ["Oulu Centre", "Oritkari", "Linnanmaa", "Kempele"], "northern city services, technology zones, industrial logistics and long regional routes", "sub-zero operation, remote-area coverage, Finnish workplace duties and technical support response"],
  ["warsaw", "Warsaw", "poland", "Poland", ["Śródmieście", "Mokotów", "Wola", "Praga"], "dense central deliveries, business districts, warehouse zones and national motorway connections", "Polish workplace and GDPR duties, low-emission access, carrier coverage and installation standards"],
  ["krakow", "Kraków", "poland", "Poland", ["Stare Miasto", "Nowa Huta", "Balice Airport", "Wieliczka"], "historic urban routes, industrial districts, airport logistics and southern Polish regional journeys", "restricted-area planning, cross-border coverage, employee policies and professional device fitting"],
  ["wroclaw", "Wrocław", "poland", "Poland", ["Stare Miasto", "Fabryczna", "Bielany Wrocławskie", "Wrocław Airport"], "city distribution, manufacturing districts, airport routes and western European freight corridors", "international roaming, Polish data rules, network reliability and secure fleet-data handling"],
  ["poznan", "Poznań", "poland", "Poland", ["Jeżyce", "Franowo", "Poznań Airport", "Swarzędz"], "commercial services, logistics estates, airport activity and major east-west transport corridors", "regional carrier performance, GDPR compliance, workplace communication and device installation"],
  ["gdansk", "Gdańsk", "poland", "Poland", ["Port of Gdańsk", "Wrzeszcz", "Oliwa", "Gdynia"], "Baltic port freight, shipyard and industrial activity, urban deliveries and northern regional routes", "port workflows, coastal weather, cross-border connectivity and durable hardware fitting"],
  ["prague", "Prague", "czech-republic", "Czech Republic", ["Prague 1", "Prague Airport", "Smíchov", "Hostivař"], "historic central routes, commercial districts, airport logistics and national motorway connections", "Czech workplace and GDPR rules, urban access, compatible networks and professional installation"],
  ["brno", "Brno", "czech-republic", "Czech Republic", ["Brno Centre", "Černovice", "Slatina", "Modřice"], "city deliveries, technology campuses, industrial estates and routes toward Austria and Slovakia", "cross-border roaming, employee policies, regional coverage and secure data access"],
  ["ostrava", "Ostrava", "czech-republic", "Czech Republic", ["Ostrava Centre", "Vítkovice", "Hrabová", "Mošnov Airport"], "heavy industry, airport logistics, urban services and Polish-Slovak freight corridors", "industrial-site access, international coverage, device durability and alert escalation ownership"],
  ["plzen", "Plzeň", "czech-republic", "Czech Republic", ["Plzeň Centre", "Borská Pole", "Skvrňany", "Nýřany"], "urban distribution, manufacturing zones, logistics parks and western cross-border road routes", "German-border roaming, Czech data duties, installation quality and carrier compatibility"],
  ["liberec", "Liberec", "czech-republic", "Czech Republic", ["Liberec Centre", "Liberec South", "Jablonec nad Nisou", "Turnov"], "city services, manufacturing communities, mountain routes and tri-border regional journeys", "mountain and winter coverage, cross-border networks, workplace rules and technical support"],
  ["budapest", "Budapest", "hungary", "Hungary", ["City Centre", "Csepel", "Budaörs", "Budapest Airport"], "dense metropolitan deliveries, industrial zones, airport freight and Danube corridor logistics", "Hungarian data and employee duties, restricted-zone planning, roaming and device fitting"],
  ["debrecen", "Debrecen", "hungary", "Hungary", ["Debrecen Centre", "North-West Economic Zone", "Debrecen Airport", "Ebes"], "city distribution, expanding manufacturing, airport logistics and eastern regional connections", "industrial workflows, regional coverage, GDPR compliance and installation responsibility"],
  ["szeged", "Szeged", "hungary", "Hungary", ["Szeged Centre", "Szeged Industrial Park", "Algyő", "Röszke"], "urban services, industrial activity, border approaches and southern Hungarian freight routes", "border-route roaming, carrier reliability, employee policies and authorized data handling"],
  ["miskolc", "Miskolc", "hungary", "Hungary", ["Miskolc Centre", "Diósgyőr", "Miskolc Industrial Park", "Tiszaújváros"], "city deliveries, manufacturing districts, industrial corridors and north-eastern regional routes", "terrain and regional coverage, device compatibility, Hungarian data duties and support ownership"],
  ["gyor", "Győr", "hungary", "Hungary", ["Győr Centre", "Győr Industrial Park", "Gönyű Port", "Mosonmagyaróvár"], "automotive industry, Danube port logistics, urban operations and Austrian-Slovak corridors", "cross-border connectivity, industrial access, GDPR responsibilities and rugged installation"],
  ["bucharest", "Bucharest", "romania", "Romania", ["City Centre", "Pipera", "Băneasa", "Militari"], "large metropolitan services, business districts, airport approaches and national distribution routes", "Romanian workplace and GDPR duties, urban traffic workflows, coverage and installation standards"],
  ["cluj-napoca", "Cluj-Napoca", "romania", "Romania", ["Cluj Centre", "Tetapolis", "Apahida", "Cluj Airport"], "technology districts, city deliveries, airport logistics and Transylvanian regional journeys", "regional and terrain coverage, employee policies, compatible networks and secure data access"],
  ["timisoara", "Timișoara", "romania", "Romania", ["Timișoara Centre", "Freidorf", "Ghiroda", "Timișoara Airport"], "urban distribution, manufacturing zones, airport freight and western cross-border corridors", "international roaming, Romanian data requirements, network reliability and device fitting"],
  ["iasi", "Iași", "romania", "Romania", ["Iași Centre", "Tătărași", "Miroslava", "Iași Airport"], "city services, technology and industrial zones, airport routes and eastern regional operations", "regional carrier coverage, workplace requirements, installation responsibility and support response"],
  ["constanta", "Constanța", "romania", "Romania", ["Port of Constanța", "City Centre", "Agigea", "Mihail Kogălniceanu Airport"], "Black Sea port freight, urban delivery, industrial areas and national road connections", "port access, coastal conditions, device durability and GDPR-compliant fleet-data handling"],
  ["athens", "Athens", "greece", "Greece", ["Athens Centre", "Piraeus Port", "Elefsina", "Athens Airport"], "dense city deliveries, major port logistics, industrial corridors and airport freight routes", "Greek workplace and GDPR duties, restricted-zone access, heat-resistant fitting and coverage"],
  ["thessaloniki", "Thessaloniki", "greece", "Greece", ["City Centre", "Port of Thessaloniki", "Sindos", "Thessaloniki Airport"], "port freight, industrial estates, urban services and Balkan cross-border connections", "port workflows, international roaming, carrier compatibility and professional installation"],
  ["patras", "Patras", "greece", "Greece", ["Patras Centre", "Port of Patras", "Vrachnaiika", "Rio"], "ferry and port activity, city distribution, coastal services and western Greek road corridors", "ferry-route connectivity, coastal coverage, employee policies and device maintenance"],
  ["heraklion", "Heraklion", "greece", "Greece", ["Heraklion Centre", "Heraklion Port", "Heraklion Airport", "Gazi"], "island deliveries, port and airport logistics, tourism transport and regional Cretan routes", "island network coverage, seasonal demand, Greek data rules and installation durability"],
  ["larissa", "Larissa", "greece", "Greece", ["Larissa Centre", "Larissa Industrial Area", "Giannouli", "Volos Corridor"], "regional distribution, agricultural logistics, industrial activity and central mainland journeys", "rural-route coverage, heat conditions, compatible SIM plans and fleet alert ownership"],
  ["istanbul", "Istanbul", "turkey", "Turkey", ["European Side", "Asian Side", "Ambarlı Port", "Istanbul Airport"], "high-density cross-city routes, major port freight, airport logistics and intercontinental connections", "Turkish data and workforce rules, bridge and tunnel coverage, device compatibility and fitting"],
  ["ankara", "Ankara", "turkey", "Turkey", ["Çankaya", "İvedik", "Sincan", "Esenboğa Airport"], "government and commercial districts, industrial zones, airport activity and central Anatolian routes", "regional coverage, Turkish employee policies, installation standards and secure data handling"],
  ["izmir", "Izmir", "turkey", "Turkey", ["Konak", "Port of Izmir", "Kemalpaşa", "Adnan Menderes Airport"], "Aegean port freight, urban delivery, industrial areas and airport-linked regional services", "port conditions, carrier performance, heat-resistant hardware and alert access responsibility"],
  ["bursa", "Bursa", "turkey", "Turkey", ["Bursa Centre", "Nilüfer", "Demirtaş", "Gemlik Port"], "automotive manufacturing, city distribution, industrial estates and port-linked freight movements", "industrial-site requirements, network compatibility, device durability and workforce communication"],
  ["antalya", "Antalya", "turkey", "Turkey", ["Antalya Centre", "Antalya Airport", "Aksu", "Manavgat"], "airport logistics, tourism transport, coastal deliveries and longer Mediterranean service routes", "seasonal operating demand, coastal and rural coverage, installation quality and data retention"],
  ["tokyo", "Tokyo", "japan", "Japan", ["Chiyoda", "Shinjuku", "Ota", "Tokyo Bay"], "high-density central deliveries, commercial districts, airport approaches and bay-area logistics corridors", "Japanese device certification, workforce privacy, dense-city signal conditions and professional fitting"],
  ["osaka", "Osaka", "japan", "Japan", ["Umeda", "Nanko", "Sakai", "Higashiosaka"], "metropolitan distribution, port terminals, manufacturing districts and Kansai regional routes", "port workflows, supported Japanese networks, employee policies and secure fleet-data access"],
  ["yokohama", "Yokohama", "japan", "Japan", ["Yokohama Port", "Minato Mirai", "Tsurumi", "Kohoku"], "major port operations, waterfront business districts, industrial zones and Greater Tokyo connections", "port access, network compatibility, device installation standards and data-retention controls"],
  ["nagoya", "Nagoya", "japan", "Japan", ["Nagoya Station", "Nagoya Port", "Minato Ward", "Komaki"], "automotive manufacturing, port freight, urban distribution and central Japanese expressway corridors", "industrial-site procedures, hardware certification, carrier coverage and alert escalation ownership"],
  ["fukuoka", "Fukuoka", "japan", "Japan", ["Hakata", "Fukuoka Airport", "Island City", "Kitakyushu Corridor"], "city deliveries, airport logistics, port-linked distribution and routes across northern Kyushu", "regional carrier performance, Japanese privacy duties, installation quality and support response"],
  ["seoul", "Seoul", "south-korea", "South Korea", ["Gangnam", "Jung District", "Guro", "Gimpo Airport"], "dense metropolitan services, commercial districts, industrial areas and airport-linked delivery routes", "Korean device certification, employee privacy, urban connectivity and local-language operations"],
  ["busan", "Busan", "south-korea", "South Korea", ["Busan Port", "Haeundae", "Gangseo", "Sasang"], "major container terminals, coastal industry, commercial routes and southern national freight corridors", "port workflows, device compatibility, carrier coverage and durable professional installation"],
  ["incheon", "Incheon", "south-korea", "South Korea", ["Incheon Airport", "Incheon Port", "Songdo", "Namdong"], "international air cargo, port freight, free economic zones and Greater Seoul logistics routes", "airport and port permissions, Korean data duties, network reliability and secure alert access"],
  ["daegu", "Daegu", "south-korea", "South Korea", ["Daegu Centre", "Seongseo Industrial Complex", "Dalseong", "Daegu Airport"], "urban distribution, textile and manufacturing districts, airport services and inland regional journeys", "industrial access, mobile-network support, workplace requirements and device maintenance ownership"],
  ["daejeon", "Daejeon", "south-korea", "South Korea", ["Dunsan", "Daedeok", "Yuseong", "Sintanjin"], "central logistics, research districts, industrial routes and national expressway connections", "regional coverage, Korean privacy policies, compatible hardware and professional installation responsibility"],
  ["bangkok", "Bangkok", "thailand", "Thailand", ["Central Bangkok", "Lat Krabang", "Bang Na", "Khlong Toei Port"], "dense city deliveries, port activity, industrial districts and airport logistics across Greater Bangkok", "Thai network and device requirements, urban traffic workflows, heat-resistant fitting and data policies"],
  ["chiang-mai", "Chiang Mai", "thailand", "Thailand", ["Old City", "Chiang Mai Airport", "San Kamphaeng", "Lamphun"], "urban services, airport routes, tourism transport and northern regional distribution journeys", "mountain and rural coverage, seasonal demand, compatible SIM plans and installation support"],
  ["phuket", "Phuket", "thailand", "Thailand", ["Phuket Town", "Phuket Airport", "Patong", "Chalong"], "island deliveries, airport logistics, tourism fleets and coastal commercial routes", "island network performance, seasonal fleet capacity, device durability and authorized data use"],
  ["pattaya", "Pattaya", "thailand", "Thailand", ["Central Pattaya", "Jomtien", "Laem Chabang", "Sattahip"], "tourism transport, port-linked freight, urban services and eastern coastal corridor operations", "port and tourism workflows, mobile coverage, Thai workplace duties and professional device fitting"],
  ["chonburi", "Chonburi", "thailand", "Thailand", ["Chonburi City", "Amata City", "Laem Chabang Port", "Si Racha"], "industrial estates, container port traffic, manufacturing logistics and Eastern Economic Corridor routes", "industrial access, carrier reliability, compatible devices and fleet alert escalation ownership"],
  ["jakarta", "Jakarta", "indonesia", "Indonesia", ["Central Jakarta", "Tanjung Priok", "Cakung", "Soekarno-Hatta Airport"], "high-density metropolitan deliveries, container port freight, industrial zones and airport logistics", "Indonesian device and network rules, traffic workflows, installation quality and secure data handling"],
  ["surabaya", "Surabaya", "indonesia", "Indonesia", ["Surabaya Centre", "Tanjung Perak Port", "Rungkut", "Sidoarjo"], "major port operations, industrial estates, city distribution and routes across East Java", "port conditions, regional carrier coverage, device durability and support responsibility"],
  ["bandung", "Bandung", "indonesia", "Indonesia", ["Bandung Centre", "Gedebage", "Cimahi", "Padalarang"], "urban deliveries, textile and manufacturing districts, warehouse areas and West Java corridors", "mountain-route coverage, congestion planning, compatible SIMs and professional installation"],
  ["medan", "Medan", "indonesia", "Indonesia", ["Medan Centre", "Belawan Port", "Kualanamu Airport", "Deli Serdang"], "city services, port freight, airport logistics and distribution routes across North Sumatra", "regional network performance, port workflows, device compatibility and authorized fleet-data access"],
  ["makassar", "Makassar", "indonesia", "Indonesia", ["Makassar Centre", "Soekarno-Hatta Port", "Biringkanaya", "Sultan Hasanuddin Airport"], "eastern Indonesian port logistics, airport freight, urban distribution and regional supply routes", "island connectivity, coastal conditions, installation standards and technical support availability"],
  ["ho-chi-minh-city", "Ho Chi Minh City", "vietnam", "Vietnam", ["District 1", "Cat Lai Port", "Tan Binh", "Thu Duc City"], "dense metropolitan deliveries, container port activity, airport districts and southern industrial corridors", "Vietnamese telecommunications rules, traffic conditions, device fitting and data-access controls"],
  ["hanoi", "Hanoi", "vietnam", "Vietnam", ["Hoan Kiem", "Noi Bai Airport", "Long Bien", "Bac Thang Long"], "central services, airport logistics, industrial zones and northern regional distribution routes", "Vietnamese network compatibility, workforce requirements, installation responsibility and coverage"],
  ["da-nang", "Da Nang", "vietnam", "Vietnam", ["Hai Chau", "Da Nang Port", "Lien Chieu", "Da Nang Airport"], "central coastal deliveries, port freight, airport operations and tourism service routes", "coastal and mountain coverage, seasonal demand, device durability and secure data handling"],
  ["hai-phong", "Hai Phong", "vietnam", "Vietnam", ["Hai Phong Centre", "Lach Huyen Port", "Dinh Vu", "Cat Bi Airport"], "deep-water port terminals, industrial parks, airport logistics and northern freight corridors", "port access, carrier reliability, Vietnamese device requirements and professional installation"],
  ["can-tho", "Can Tho", "vietnam", "Vietnam", ["Ninh Kieu", "Cai Cui Port", "Tra Noc", "Can Tho Airport"], "Mekong Delta distribution, port activity, industrial zones and regional agricultural supply routes", "rural and river-route coverage, climate conditions, compatible SIM plans and support ownership"],
  ["manila", "Manila", "philippines", "Philippines", ["Port Area", "Binondo", "Malate", "Tondo"], "dense city deliveries, major port freight, commercial districts and Metro Manila service routes", "Philippine privacy and employment duties, congestion workflows, network coverage and fitting"],
  ["quezon-city", "Quezon City", "philippines", "Philippines", ["Cubao", "Diliman", "Novaliches", "Eastwood"], "large metropolitan service territories, commercial districts, warehouse routes and scheduled deliveries", "urban carrier performance, device compatibility, employee policies and fleet-data access controls"],
  ["cebu-city", "Cebu City", "philippines", "Philippines", ["Cebu Port", "Cebu Business Park", "Mactan", "Mandaue"], "port and airport logistics, business districts, industrial routes and island-wide distribution", "island network coverage, port workflows, installation quality and ongoing platform support"],
  ["davao-city", "Davao City", "philippines", "Philippines", ["Davao Centre", "Sasa Wharf", "Buhangin", "Davao Airport"], "southern regional distribution, port activity, airport freight and long Mindanao service routes", "regional and rural coverage, compatible SIM plans, device durability and data retention"],
  ["makati", "Makati", "philippines", "Philippines", ["Makati CBD", "Chino Roces", "Guadalupe", "Bonifacio Corridor"], "high-density business deliveries, commercial services, warehouse connections and Metro Manila routes", "privacy and workplace requirements, congestion planning, professional fitting and alert ownership"],
];

export const internationalCities: InternationalCitySeo[] = [
  ...initialInternationalCities,
  ...expansionCitySeeds.map(
    ([slug, name, countrySlug, countryName, areas, routeProfile, planningFocus]) =>
      createInternationalCity({
        slug,
        name,
        countrySlug,
        countryName,
        areas,
        routeProfile,
        planningFocus,
      }),
  ),
];

export function getInternationalCity(slug: string) {
  return internationalCities.find((city) => city.slug === slug);
}

export function generateInternationalCityKeywords(city: InternationalCitySeo) {
  return [...new Set([
    `GPS tracker ${city.name}`,
    `GPS tracker in ${city.name}`,
    `vehicle tracking system ${city.name}`,
    `fleet tracking ${city.name}`,
    `fleet management software ${city.name}`,
    `commercial vehicle tracking ${city.name}`,
    `truck GPS tracking ${city.name}`,
    `GPS tracker ${city.name} ${city.countryName}`,
    ...city.areas.map((area) => `GPS tracker ${area}`),
  ])];
}

export function generateInternationalCityMetadata(city: InternationalCitySeo): Metadata {
  const url = `https://naviigps.com/gps-tracker/${city.slug}`;
  const description = `GPS tracking devices and fleet software planning in ${city.name}, ${city.countryName}, including routes around ${city.areas.slice(0, 2).join(" and ")}.`;

  return {
    title: `GPS Tracker in ${city.name}, ${city.countryName} | NAVII GPS`,
    description,
    keywords: generateInternationalCityKeywords(city),
    alternates: { canonical: url },
    openGraph: {
      title: `GPS Tracker in ${city.name}, ${city.countryName} | NAVII GPS`,
      description,
      url,
      type: "website",
      images: ["/og-image.jpg"],
    },
  };
}
