import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Globe2 } from "lucide-react";
import Header from "@/components/layout/HeaderV2";
import Footer from "@/components/layout/FooterV2";
import {
  generateInternationalHubKeywords,
  internationalCountries,
} from "@/lib/seo/internationalCountries";

const url = "https://naviigps.com/gps-tracker-international";
export const metadata: Metadata = { title: { absolute: "International GPS Tracking Solutions | NAVII GPS" }, description: "Explore vehicle GPS tracking and fleet software deployment guides for Gulf, Asia-Pacific, North American and European markets. Confirm deployment compatibility.", keywords: generateInternationalHubKeywords(), alternates: { canonical: url }, openGraph: { title: "International GPS Tracking Solutions | NAVII GPS", description: "Country guides for international vehicle tracking and fleet deployment planning.", url, type: "website", images: ["/og-image.jpg"] } };
export default function InternationalGpsPage() { return <><Header /><main><section className="bg-gradient-to-br from-[#041225] via-[#08224A] to-[#103B82] py-24 text-white md:py-32"><div className="mx-auto max-w-7xl px-6"><span className="inline-flex items-center gap-2 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-5 py-2 text-sm font-semibold tracking-widest text-cyan-200"><Globe2 size={17} /> INTERNATIONAL</span><h1 className="mt-7 max-w-5xl text-5xl font-extrabold leading-tight md:text-6xl">International GPS Tracking and Fleet Software</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">Explore country-specific planning guides for vehicle tracking devices and fleet software. Every international deployment requires confirmation of mobile-network compatibility, installation, regulations and support arrangements.</p></div></section><section className="bg-slate-50 py-20"><div className="mx-auto max-w-7xl px-6"><h2 className="text-4xl font-extrabold text-slate-900">Choose a Country Guide</h2><div className="mt-10 grid gap-6 md:grid-cols-2">{internationalCountries.map((country) => <Link key={country.slug} href={`/gps-tracker/${country.slug}`} className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm transition hover:border-cyan-500 hover:shadow-lg"><h3 className="text-2xl font-bold text-slate-900">GPS Tracker in {country.name}</h3><p className="mt-4 leading-7 text-slate-600">Planning guidance for routes around {country.cities.slice(0, 3).join(", ")} and other operating locations.</p><span className="mt-6 inline-flex items-center gap-2 font-semibold text-blue-700">View country guide <ArrowRight size={17} /></span></Link>)}</div></div></section><section className="bg-[#06142E] py-16 text-white"><div className="mx-auto max-w-5xl px-6 text-center"><h2 className="text-4xl font-extrabold">Discuss Your International Fleet Requirements</h2><p className="mx-auto mt-4 max-w-3xl leading-7 text-slate-300">Share the target country, vehicles, routes, required features and expected rollout size.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-7 py-4 font-semibold">Contact NAVII GPS <ArrowRight size={19} /></Link></div></section></main><Footer /></>; }
